### ISSUE TITLE
Crash after Startup

### ISSUE THREAD

**Issue by pewblaze** [Globox1997/tiered#1]
Game crashes after startup :( Not sure why.
Fabric Loader 0.13.3
tiered-1.0.0

https://gist.github.com/pewblaze/3ec0379d29436db563915d3ad1b8fa74

**Comment by Globox1997** [comment]
Was an unlucky incompatibility with fabric api, since they added something this mod already did.
Fixed with [https://github.com/Globox1997/tiered/commit/6c45bf18768ca0ed773c7050b6bece1a21d7d1f9](https://github.com/Globox1997/tiered/commit/6c45bf18768ca0ed773c7050b6bece1a21d7d1f9)
