### ISSUE TITLE
Game crashes not sure why 

### ISSUE THREAD

**Issue by Jaycords** [Globox1997/tiered#104]
### Minecraft Version

1.20.x

### Mod Loader Version

47.2.17 not fabric but forge

### Mod Version

1.20.1 - 6.0.3

### Describe the Issue

playing a bettermc forge playthrough and wanted to add teird and it wouldn't boot up for some reason its strange 

### latest.log

[crash-2024-03-09_17.05.20-fml.txt](https://github.com/Globox1997/tiered/files/14547951/crash-2024-03-09_17.05.20-fml.txt)

### Do you use any other mods except the required ones?

yes.

**Comment by Globox1997** [comment]
O.o I only support fabric out of time reasons.
