### ISSUE TITLE
Blacklist for special case items

### ISSUE THREAD

**Issue by Hyomoto** [Globox1997/tiered#106]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

The Create airtank is unique in that when it's placed in the world it becomes a block, and when broken it becomes a brand new item.  I feel like the simplest fix here is just to have certain items that can be blacklisted and will never have a tier assigned to them.  But while this itself might be a bug, there are cases where special items might not really make sense to *have* randomized tiers.  For example, a new mod Blossom Blade puts a special sword in the world: can I find a common legendary sword?  Bit weird.  This is something I don't think any mod maker could fully hope to encapsulate and as such, the ability to remove items from the tiered influence is desirable.

**Comment by Globox1997** [comment]
Added a restriction item tag with [https://github.com/Globox1997/tiered/commit/d2405bc3864c3925342f8e295ad0680d8e364222](https://github.com/Globox1997/tiered/commit/d2405bc3864c3925342f8e295ad0680d8e364222).
Just add the item to the tag.
