### ISSUE TITLE
Incompatibility with BCLib, Reforged button on anvil doesn't work

### ISSUE THREAD

**Issue by ConqAra** [Globox1997/tiered#11]
I'm trying to click on the reforge button in the anvil menu and it just doesn't work.

**Comment by ConqAra** [comment]
May have to do something with a mod incompatibility? I can send my log but i dont see an error for this. 

Log: [https://paste.ee/p/3InhH](https://paste.ee/p/3InhH)

**Comment by Globox1997** [comment]
Mh this is pretty bad, the good thing is you only have quadrillion mods installed xD
I have no idea what could cause this issue, maybe a screen editing mod

**Comment by Leonelecg** [comment]
I have the same problem, and I found out why, I guess it's an incompatibility with BCLib



Here is the BCLib curseforge link: https://www.curseforge.com/minecraft/mc-mods/bclib

**Comment by jklw10** [comment]
Can confirm, button doesn't work and I do have BCLib but I cannot know if that's the one mod that causes this. I'm unsure because i don't know if bclib itself changes the anvil menu in any way?

**Comment by Globox1997** [comment]
If you guys can narrow down the incompatibility, that would be super helpful :)
I will look into it when I have time for modding again

**Comment by Leonelecg** [comment]
I'm pretty sure BCLib is what's causing the error, maybe some kind of incompatibility

**Comment by jklw10** [comment]
I think a good temporary fix would be to add a keybind to switch to reforge screen...

**Comment by Globox1997** [comment]
Pretty sure this is the issue: [https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/mixin/common/AnvilMenuMixin.java#L180](https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/mixin/common/AnvilMenuMixin.java#L180)
BCLib overrides the onclick method (different mappings) so the tiered injection won't get used
Can't make it compatible from my side, except adding a keybind which sucks

**Comment by jklw10** [comment]
hmm i assume you'll open an issue for it then. or just make a pull request with it being an injection instead of override.

**Comment by Globox1997** [comment]
I assume you will open an issue :)

**Comment by itsdinkd** [comment]
You guys are lazy! I'll open the issue.

**Comment by itsdinkd** [comment]
> I assume you will open an issue :)

Please respond to the developer in the ticket I opened on their github. It's linked here

**Comment by venny-ven** [comment]
Please address this

> Any plans of applying these fixes to 1.18.2?

> Yes, but there is no ETA as it currently has low priority. As far as I can tell, TieredZ can just change the mixing priority to override ours. Which should be absolutely fine. Our mixing is there to show UI in case there are multiple recipes for the same list of ingredients. I think that is not uses in 1.18.2 anyway.
- https://github.com/quiqueck/BCLib/issues/28
