### ISSUE TITLE
Reforge Mechanic Limitations.

### ISSUE THREAD

**Issue by RulOfficial** [Globox1997/tiered#110]
### Description of your suggestion.

It would be nice to have a way to limit who can reforge weapons and who can't, I've tried to stop the tab inside the anvil from rendering for players with a specific tag, but to no avail, do you think there would be an easy way to do it?

**Comment by RulOfficial** [comment]
I got it on my own.

**Comment by Globox1997** [comment]
How?

**Comment by RulOfficial** [comment]
On the onClick(MinecraftClient client) in ReforgedTab.java just made an if statement, will be posting the fork in a while.
