### ISSUE TITLE
[Request] Config Entry for Reroll item

### ISSUE THREAD

**Issue by itsdinkd** [Globox1997/tiered#12]
Would help modpack devs if you created a entry in the config to allow creators to choose which item is the source item required to re-roll

**Comment by Globox1997** [comment]
The mechanic of tiered doesn't allow specific reroll items for specific items but check the tags [https://github.com/Globox1997/tiered/tree/1.18/src/main/resources/data/tiered/tags/items](https://github.com/Globox1997/tiered/tree/1.18/src/main/resources/data/tiered/tags/items)

**Comment by itsdinkd** [comment]
> The mechanic of tiered doesn't allow specific reroll items for specific items but check the tags https://github.com/Globox1997/tiered/tree/1.18/src/main/resources/data/tiered/tags/items

Yep I know. I'm requesting that it be added so I as a modpack developer can make the mechanic balanced. It doesn't need to be a specific reroll item for specific items, but allow to choose what item is required for rerolling in general.

**Comment by itsdinkd** [comment]
Ah okay I see now. It's a tag. Cool thanks
