### ISSUE TITLE
Incompatibility with Inventory Tabs

### ISSUE THREAD

**Issue by venny-ven** [Globox1997/tiered#13]
Inventory Tabs obscure the Reforge Gear tab in the anvil. Clicking on this "double tab" crashes the game. I strongly suggest against adding tabs to an anvil and instead use a separate block for reforging. Or maybe repurpose the grindstone. But do not add tabs please.

![image](https://user-images.githubusercontent.com/70820375/184384509-a86b09a8-584c-4c39-ab89-90aef6ee3390.png)

**Comment by Globox1997** [comment]
Added a tab config with [https://github.com/Globox1997/tiered/commit/5d7373274797facfbbc85218ad5f218fe5c67e07](https://github.com/Globox1997/tiered/commit/5d7373274797facfbbc85218ad5f218fe5c67e07) to disable/remove the reforge tab. I have no plans to add a separate reforging block

**Comment by KB-Q** [comment]
Any update on making this compatible? I think you can modify it so that clicking on the hammer icon in the anvil switches it between anvil mode and reforging mode.

**Comment by Globox1997** [comment]
I have no plans to make it compatible with inventory tabs. Might change in the future.
