### ISSUE TITLE
Origin Classes incompatibility with TieredZ

### ISSUE THREAD

**Issue by xErrorAmelie** [Globox1997/tiered#15]
So I found a bug where you can't get TieredZ attributes on swords and armor when you select the blacksmith origin in Origin Classes.
I thought it could help when I open up an issue here as well.

More details are on their github: https://github.com/apace100/origins-classes/issues/66

**Comment by Globox1997** [comment]
Is this still the case on the latest version?

**Comment by xErrorAmelie** [comment]
> 

Yes, I tested it again now with the latest versions of your and their mod.

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest versions of my mods, if you use the latest version and this bug still occurs, please reopen this issue.
