### ISSUE TITLE
1.19.2? 

### ISSUE THREAD

**Issue by ramblinghaggis** [Globox1997/tiered#17]
Hey Globox, are you planning on a version for 1.19.2? Had a shot at trying to update tieredz myself but got stuck on one part of the code!

**Comment by Globox1997** [comment]
Yes but this mod depends on the autotag mod which has to update first on 1.19.2 :)

**Comment by ramblinghaggis** [comment]
Yes I noticed that, you have done commitments for auto tag for 1.9 haven’t you? So it needs apace100 to merge, is that right? I will be patient, I’m just super pleased it’s going to happen!

**Comment by Globox1997** [comment]
Updated to 1.19.2 :)
