### ISSUE TITLE
Armor re-calculates?

### ISSUE THREAD

**Issue by Linext23** [Globox1997/tiered#24]
Sooo the title says it all. Getting hit makes the armor bar seem to recalculate the armor and toughness and all the other effects of the prefixes

**Comment by Globox1997** [comment]
Should be fixed with the latest commits

**Comment by Linext23** [comment]
> Should be fixed with the latest commits

Ah thank you, built the latest commit and it works. Keep up the hard and good work!

**Comment by Linext23** [comment]
Sooo bad idea trying it on a server LOL, i'll just wait for an Official update but it seems to be going along nice.
And the tooltips seem to not follow enchant updates either lol and this on the non-host end (just in-case it helps, posting this picture)
![image](https://user-images.githubusercontent.com/26930675/200754395-8242c3e6-192e-43b8-a921-7156cd0f8c3a.png)

**Comment by Globox1997** [comment]
What exactly are the issues?

**Comment by Linext23** [comment]
> What exactly are the issues?

So the issue was, the armor recalculates when hit by anything and in the latest commit (like you said), yes it seemed to have fixed that, however, it caused other issues as you can see in the image above when non-host tries to join. 

One other issue i can note about atm is that the Reforges/prefixes mess up enchants modifying the tooltip. (They still apply to the weapon but the tooltip doesn't reflect it when reforged and/or breaks it entirely

This should be 24 (+15% Damage)
![image](https://user-images.githubusercontent.com/26930675/201153125-7495331c-9091-40d8-bf45-4fd8c53dce19.png)
 
 Here's a normal Netherite Sword as a test
 ![image](https://user-images.githubusercontent.com/26930675/201153233-8fe0e7b7-11cc-4c6a-9134-6ad0ff179bc4.png)
![image](https://user-images.githubusercontent.com/26930675/201153455-6321f605-488c-4836-8bbc-9628ec2890da.png)
![image](https://user-images.githubusercontent.com/26930675/201153627-51a6a067-7057-4de2-a234-fcad79ac8e9d.png)

It seems if something modifys a stat on whatever is reforged that already has the stat (in this case a sword, modded or not) it stops visibly showing that the enchants are applied to the weapon but the enchants still function as normal. 

![image](https://user-images.githubusercontent.com/26930675/201154290-7a18ab66-e4eb-423f-9e03-b69561db0ef6.png)
(Just figured this out) It even applies to attack speed but this time nothing is modifying it but the reforge, however it still attacks with -25% instead of the so called -2.4 attack speed, so it seems the issue isn't just in the enchants visually, the reforges visually update the tooltip wrong anyways (IF it adds or subtracts to a stat that's already there.)

These are the issues i've found so far

**Comment by Globox1997** [comment]
fixed it with [https://github.com/Globox1997/tiered/commit/154e512e533cf81906bb98075717a020b8776a8d](https://github.com/Globox1997/tiered/commit/154e512e533cf81906bb98075717a020b8776a8d)
