### ISSUE TITLE
[Suggestion] Add min/max number providers for "amount" function in tiers

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Globox1997/tiered#26]
I don't think any loot tables in vanilla Minecraft use the min/max number providers for attribute "amount", but it can be done in vanilla for custom loot tables, for example this loot table I made: https://pastebin.com/Leyu9Td7 . As you can see, the attack damage modifier and the attack speed modifiers are using min/max, meaning you will get a random attack damage/attack speed somewhere between the min/max. I would like if this was supported in Tiers, as it allows for far more randomization and can make things even more interesting. For example, here is the Hasteful tier with the min/max number providers: https://pastebin.com/QRPXHeFM . It would average out to give players the same +10% dig speed, but if you are unlucky you could get only +5%, or if you are very lucky you could get +15%!

**Comment by RobertHDPotatoes** [comment]
Sorry about the messed up formatting in the first pastebin. Not sure what happened there

**Comment by Globox1997** [comment]
This is currently not doable with the implemented system

**Comment by MJRamon** [comment]
Yes, this one is great and needed!

**Comment by Globox1997** [comment]
Lately I have no plans to add such a system.
