### ISSUE TITLE
[Suggestion] Compatibility with modded weapons

### ISSUE THREAD

**Issue by TheKyuke** [Globox1997/tiered#27]
Would it be possible to add support for modded weapons ?
1. **Reforging them with the correspondent ore/item**
(or if it's easier, letting us add them via the config file)
![Screenshot_1 (Petite) (Personnalisé)](https://user-images.githubusercontent.com/36053666/201390853-c800044b-f812-4069-9de8-53f08c7c7bb4.png)

2. **Applying modifiers when looting them in chest/dungeons**

Besides that, do you plan on adding other modifiers in future updates ?
Thank you for your time and dedication to this mod 👍🏻

**Comment by Globox1997** [comment]
This can definitely be done with a datapack already. Check out the readme.
