### ISSUE TITLE
Health bonus resets upon item losing durrability.

### ISSUE THREAD

**Issue by EtsanMC** [Globox1997/tiered#28]
I've been playing for a little bit with this mod and I have a stone pickaxe that gives me a health bonus. Whenever it loses durability upon usage the filled bonus hearts reset to empty hearts causing me to regenerate and lose hunger. When I'm mining I'm constantly needing to eat after I mine to fill the bonus hearts and refill my hunger.

**Comment by jmadarg** [comment]
I'm having the same issue, and it does happens with the armor too

**Comment by BrokenRepository** [comment]
Having a similar issue after updating this mod and a lib it depends on, plus a few others. We have been trying to find out what to roll back to get it working again.

**Comment by Globox1997** [comment]
This is probably fixed with a later update
