### ISSUE TITLE
MInecraft bows

### ISSUE THREAD

**Issue by Chief0609** [Globox1997/tiered#29]
This isnt really an issue, it might be idk i couldnt find a "questions" category so ill ask here, how do you reroll a bows Tier? Ive tried with string, sticks even normal materials like iron, diamonds etc. Is there a way to reroll it?

**Comment by Chief0609** [comment]
Also ive tried just crafting a crap ton and do bows have a legendary Tier like weapons and armor?

**Comment by Globox1997** [comment]
With the coming update there will be an info which material is needed
Also, the default datapack will get an overhaul 
Bows doesn't if I remember correctly

**Comment by Chief0609** [comment]
Alr thank you sir
