### ISSUE TITLE
Issues with TierZ and LevelZ

### ISSUE THREAD

**Issue by Chief0609** [Globox1997/tiered#31]
I have an issue to where i set the max level for LevelZ to 50 to make it more challenging, and once i put my luch past lvl22 the tierZ mod suddenly stops working, for no reason. Its on the newest Version released today, and i tried the version before that and both didnt work. Has anyone else had this problem?

**Comment by Globox1997** [comment]
What do you mean by suddenly stops working? What exactly doesn't work anymore
and please provide the latest.log file
