### ISSUE TITLE
Making TieredZ expandable: expensive random control

### ISSUE THREAD

**Issue by MJRamon** [Globox1997/tiered#33]
I believe this very needed features will take TieredZ to next level. Yeah, I know, cheesy pitch, but hear me out :)

1. Making it so gear will not recieve random stats on craft (config option). Thus if **you want stats - you use Reforge**.
2. Maybe even add separate block for Reforge (with expensive recipe for it. **Anvil is cheap**!).
3. Setting custom tiering item material (left slot) and reforge addition item (right slot) in Reforge (with count). is very needed, for **getting specific upgrades**.
Let's say, I want damage - I use 1 diamond and 5 quartz and get a random tier of a stat for this resources combination. I want speed? I use 1 emerald and 16 redstone, and repeat it until I get a better tier of damage (or speed, or anything else).
This leaves **current system intact**: using default items will give default stat bundles. But using specific combinations will give specific stats - you still need to "fish" for better numbers, **paying resources for a better control**.
4. This leads us to one more thing: **dynamically changing or adding specific upgrades**. For example, I've got random +damage, and now I use specific resources to modify it, fishing for better damage tier - without wiping out everything else (like it does if rerolled).
5. Lastly, a way to limit number of upgrade "slots" for an item, if they are added one by one with specific resources, or deny adding more and more if used a "bundle" upgrade. Best way is with tags, I guess: tiered_1_slot.json, tiered_2_slot.json, tiered_3_slot.json and so on. Adding tags or item ids in these tags will set the **maximum amount of modifiers**. "Bundles" will ignore this, giving as much modifiers as is set in json, wiping everything it had before (as it is now).

**Comment by Globox1997** [comment]
1. done, check out the config.
2. no plans to do 
3. also no plans for that but you can set specific reforge items with a datapack
4. I know it is disappointing but my available time is too short to work on such a system 
5. ...
