### ISSUE TITLE
Crash Report Crafting

### ISSUE THREAD

**Issue by LadySunx** [Globox1997/tiered#34]
Modpack: Medieval MC [FABRIC] - MMC1 (Just in case you needed to know.)

Crashes when i make an item from the crafting interface. 

https://mclo.gs/7J5PDUz

**Comment by Globox1997** [comment]
Mh I wonder why this happens. Turn off the tieredTooltip  setting in the config

**Comment by Globox1997** [comment]
Probably got fixed with a later update.
