### ISSUE TITLE
Crash report with rendering

### ISSUE THREAD

**Issue by benio1394** [Globox1997/tiered#35]
https://pastebin.com/GT2Mr7gB

**Comment by xErrorAmelie** [comment]
I can confirm this with a steam drill from modern industrialization and tiered installed. 
**Crashlog:** 
https://mclo.gs/rLhOQXq
**Tiered Version:** 
1.2.1
**How to reproduce:** 
Hover over the item.
**How to temporarily fix it:** 
Disable Tiered Tooltips in the mod ingame settings.

**Comment by xErrorAmelie** [comment]
Another crash with Tooltips, but slightly different: https://mclo.gs/PGh9LIT
Happend with just opening my inventory, I didn't hover over anything to my knowledge.

**Comment by Globox1997** [comment]
Got fixed with a later update.
