### ISSUE TITLE
Does this work with 1.190?

### ISSUE THREAD

**Issue by Soggyshorts** [Globox1997/tiered#36]
I'm compiling a list, but can't test at the moment, just wondering if this works in 1.190, and 1.192 as well as 1.192
Thanks!

**Comment by xR4YM0ND** [comment]
The newest versions (1.1.1 - 1.2.1) work for Minecraft Version 1.19.2 (Fabric) , for 1.19.2 and even for 1.19.2
Pleasure!

**Comment by Soggyshorts** [comment]
> The newest versions (1.1.1 - 1.2.1) work for Minecraft Version 1.19.2 (Fabric) , for 1.19.2 and even for 1.19.2 Pleasure!

But... those are all the same. Does it work with 1.19.0?

**Comment by xR4YM0ND** [comment]
I dont think so, but you can test it.

**Comment by xR4YM0ND** [comment]
Test it when you have time
