### ISSUE TITLE
[Compat] Cammies Backpacks - Crafting Table - No Rarity gets applied - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/tiered#37]
When you use the build in crafting tables in the backpacks, the item only gets a rarity when you drag & drop it in your inventory.

If you shift left click the crafting output, (the e.g. armor) gets first in the equiped slot ( without rarity ) and when the slot is already filled, the armor gets destroyed 

Newest Fabric / TieredZ / Cammies Backpacks

https://www.curseforge.com/minecraft/mc-mods/cammies-wearable-backpacks

**Comment by Globox1997** [comment]
Have no plans to add compatibility from my side.
