### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Qwazxz** [Globox1997/tiered#39]
Game crashes when ever i hover any item with stats eg. spade or pickaxe, either in storage or inventory.

[crash-2022-12-27_23.59.59-client.txt](https://github.com/Globox1997/tiered/files/10311044/crash-2022-12-27_23.59.59-client.txt)
[crash-2022-12-28_00.09.03-client.txt](https://github.com/Globox1997/tiered/files/10311045/crash-2022-12-28_00.09.03-client.txt)
[crash-2022-12-27_23.33.00-client.txt](https://github.com/Globox1997/tiered/files/10311046/crash-2022-12-27_23.33.00-client.txt)
[crash-2022-12-27_23.38.55-client.txt](https://github.com/Globox1997/tiered/files/10311047/crash-2022-12-27_23.38.55-client.txt)

**Comment by Globox1997** [comment]
Got fixed with a later update.
