### ISSUE TITLE
Immersion-ruining bugs and some content suggestions

### ISSUE THREAD

**Issue by radicalaction** [Globox1997/tiered#4]
First of all, bugs. Tools and armor generated in dungeons are always default minecraft ones with no tieredz modifiers. At the same time, items bought from villagers have modifiers but no colored name with prefix. /* Second, legendary tooltips issues. I spent whole night trying to figure out how does that priority system works and had almost no success. I installed eclectic trove resourcepack and I found that "all" modifiers always have first left five options on a gui atlas. Common is always golden one, uncommon is always silver, rare is bronze and so on. And it can't be changed with configs or resourcepack json editing. I can change more specific prefixes (e.g sharp or berserk) and choose another texture but not "all" modifiers - common, uncommon, rare, epic, legendary and extended. I know that legendary tooltips is not your project but I saw legendarytooltips folder in your mod so I thought that you might be interested in adding better compat. */ Okay, I think that's all I wanted to say about bugs. Quality tools mod had a reforging station if I remember correctly. It had a slot for a tool and a slot for a respective ingot or gem. Like if you crafted a dull diamong sword and upset about it you just spend one more diamond to test your luck again. It's not that cool to craft tons of diamond swords trying to get a legendary one. Another variant is to make special items for reforging tools and armor. Have you ever played path of exile? Do you know how their currency system works? It's awesome and I think it'll fit with tieredz, especially in tandem with levelz. Here's how you can adapt it to minecraft: you have a pool of affixes for items (like +2-5 HP, +10-15% damage, +2-5 armor, [-10%;+10%] movement speed or attack speed, but for now they're almost tied to name prefixes and inaccessible with configs), and for every created item math rolls for rarity first, then math rolls for bonuses from pool (e.g an rare item gets +4 HP, +2 armor and +5% attack speed), and then math rolls inside these specific intervals to get numbers; and these bonuses aren't tied to the name (rarity), but rarity defines how much affixes (bonuses) you get (e.g common has one bonus, uncommon has two and so on). It's a simple system but it can drag a man down for infinite grinding. What about specific items... Maybe an item for nullifying an item of any rarity to get a common one. Maybe an item for upgrading from common to uncommon with that rolls I explained earlier. Maybe an item for upgrading from uncommon to rare with older modifiers + new rolled one. I'm sorry for a wall of text but I really liked your project and it's such a pity that it feels scarce with these hardcoded stats.

EDIT: I found frame definitions file for tiered items in tiered jar, nvm

**Comment by Globox1997** [comment]
Added loot tiering with [https://github.com/Globox1997/tiered/commit/853ef2c6841c986a525a1561afb5def8739bc91c](https://github.com/Globox1997/tiered/commit/853ef2c6841c986a525a1561afb5def8739bc91c)
Yes legendary tooltips is kinda a hustle to figure out
Your text is definitely a wall xD 
A reforging station sounds cool, will think about it more :)
I never player age of exile, sounds like an interesting system but I will stick with tiereds system for now

**Comment by RobertHDPotatoes** [comment]
I would also love to see a reforging station :D

**Comment by Globox1997** [comment]
Added a reforging addition to the anvil with the last couple of commits [https://github.com/Globox1997/tiered/commit/98fa78401d788bf694bcb24288e76c59cefbfa05](https://github.com/Globox1997/tiered/commit/98fa78401d788bf694bcb24288e76c59cefbfa05)

**Comment by Globox1997** [comment]
Reopen if still some of the given requests are wanted on the latest version.
