### ISSUE TITLE
reforge not working??

### ISSUE THREAD

**Issue by Boolerino** [Globox1997/tiered#40]
most of the items i craft end up being poor quality and i'm trying to reforge them, for example: i made a Hallowed Pickaxe with the Mythic Metals mod and it came out common, i figure it's no biggie since i can reforge, but when i put in the tiered ingot, (Hallowed Ingot) and an amethyst shard as per the mod's requirements, the button to reforge still says "Required Ingredient: Hallowed Ingot" and it remains grey so that I can't reforge. Any help as to why this is happening and how I can fix it?

**Comment by KarishaDel** [comment]
I am having the same problem with any gear and material.

**Comment by Kyhrew** [comment]
For me, the solution was having the item you want to reforge, with 100% durability. any damaged items were not working.

**Comment by Globox1997** [comment]
Added full durability info with [https://github.com/Globox1997/tiered/commit/d1a67e14133c970bf2b1d0165acfb2fd621ffe13](https://github.com/Globox1997/tiered/commit/d1a67e14133c970bf2b1d0165acfb2fd621ffe13)
