### ISSUE TITLE
Modifiers do not work in left hand.

### ISSUE THREAD

**Issue by ghost** [Globox1997/tiered#41]
So, Say i have a hoe that gives me -2 reach. Everything works until i swap to my left hand and its the regular reach. This is probably due to the mod using Minecraft's base attribute system but it would be nice to see it working regardless

**Comment by chronosacaria** [comment]
@SuperMatCat24 I'm not the dev of this mod, but I am pretty sure that it actually has to do with how Minecraft handles the offhand. It doesn't, by default, respect attribute changes as well as, by default, applies enchantments and other modifiers from the offhand to the main hand (you can test this with Bane of Arthropods in your offhand and then punch a spider. It will get slowed).

Now, granted, I am theorising, but based on your description, that's what it sounds like is happening

**Comment by Noth-Shian** [comment]
Look the description of that hoe, its says ... "On main hand... -2 reach"

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/0f2e5202798e561d8cf443284e3abfd991e147dc](https://github.com/Globox1997/tiered/commit/0f2e5202798e561d8cf443284e3abfd991e147dc)
