### ISSUE TITLE
Possible Incompat with RelicEx - Can't use smithing table to apply Relic to tiered modded item

### ISSUE THREAD

**Issue by jmadarg** [Globox1997/tiered#43]
MC version: 1.19.2 Fabric
Modpack: Medieval MC [FABRIC] - MMC1
Problem: When trying to ass a Relic (they can add different new properties to items) to a modded item that has a tier, the Relic does not add any property. It works fine if the item is vanilla and has a tier, or if the item doesn't have a tier (modded or vanilla). Not always happens, I'm still not able to pinpoint exactly what triggers the problem.

Modded item without any tier:
![image](https://user-images.githubusercontent.com/62086445/213697730-c9ecc59c-19fa-415f-8a50-04998f80a2ee.png)

Modded item with a tier but not working properly:
![image](https://user-images.githubusercontent.com/62086445/213697745-72d89186-c0f2-4aec-9f03-ac3c36325fe6.png)

Modded item with a tier but working properly (was a different set of properties on the tier and a different Relic):
![image](https://user-images.githubusercontent.com/62086445/213697762-9c174fca-b0bc-41f4-88f6-1b8d43b28fed.png)

I oppened an issue on the RelicEx github too https://github.com/CleverNucleus/RelicEx/issues/32

**Comment by Yasamashi** [comment]
I also wanted to add that you can't join a vanilla armor already found enchanted (e.g.: found in a dungeon chest and the likes) and a relic in the same way: the vanilla armor doesn't get the stats even if the action is possible. Screenshots attached.

![2023-01-20_15 30 28](https://user-images.githubusercontent.com/56409190/213728726-a2df8d7e-a25e-443d-84ec-0b6ce33f87e3.png)
![2023-01-20_15 30 32](https://user-images.githubusercontent.com/56409190/213728775-43a05bd2-58ef-421e-89a3-e63a7fac562a.png)
![2023-01-20_15 30 37](https://user-images.githubusercontent.com/56409190/213728867-fa655258-c3dd-4c42-acb3-097638661fb9.png)
![2023-01-20_15 34 09](https://user-images.githubusercontent.com/56409190/213728892-0abb454a-7bbd-4859-93ef-60ba31df0b67.png)
![2023-01-20_15 34 19](https://user-images.githubusercontent.com/56409190/213728942-e18d3c56-2e47-4777-a0b5-a4d710acce8b.png)
![2023-01-20_15 34 16](https://user-images.githubusercontent.com/56409190/213728991-a7aa1b66-1591-4628-94a2-3dc239839698.png)

**Comment by Globox1997** [comment]
Fixed by relicex with [https://github.com/CleverNucleus/RelicEx/issues/32](https://github.com/CleverNucleus/RelicEx/issues/32)
