### ISSUE TITLE
`tieredTooltips` makes big tooltips to get cut off the screen

### ISSUE THREAD

**Issue by jmadarg** [Globox1997/tiered#45]
When there are big tooltips, like those added by Enchantment Descriptions, the tooltips go out of the screen even when adding mods that make text to wrap (like ToolTipFix or Debugify).

When `tieredTooltips`  is `false` the tooltip looks like this: 
![image](https://user-images.githubusercontent.com/62086445/213898854-141f2c88-c441-4d20-9e84-c41393780720.png)

But when its `true` looks like this:
![image](https://user-images.githubusercontent.com/62086445/213898866-71715697-c161-4c74-aec6-436488217d8d.png)

This is on Minecraft 1.19.2

**Comment by Globox1997** [comment]
Thanks for reporting, added compat with tooltipfix with [https://github.com/Globox1997/tiered/commit/a74a2557d288f0cc45f419645ef4bbada994d602](https://github.com/Globox1997/tiered/commit/a74a2557d288f0cc45f419645ef4bbada994d602)
