### ISSUE TITLE
Modern industrialization incompatibility 

### ISSUE THREAD

**Issue by RatDonkeyGoat** [Globox1997/tiered#46]
Basically, you'd have to change this https://github.com/Globox1997/tiered/blob/1.19/src/main/java/draylar/tiered/reforge/ReforgeScreen.java#L82
to something like
else if (itemStack.getItem() instanceof ArmorItem armorItem) {
  if (armorItem.getMaterial().getRepairIngredient() != null) {
    baseItems.addAll(Arrays.asList(armorItem.getMaterial().getRepairIngredient().getMatchingStacks()));
  }
} else {
  ...

(Didn't test it for errors and such, but that should avoid the NPE)

[latest.log](https://github.com/Globox1997/tiered/files/10474133/latest.log)

**Comment by Globox1997** [comment]
mh the repair ingredient should not be null but are there other cases like tools which have no ingredient either?

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/08d3446f769395b076af459f35238b7496666486](https://github.com/Globox1997/tiered/commit/08d3446f769395b076af459f35238b7496666486)
