### ISSUE TITLE
[Compat] Advanced Tooltips - Hovering over Armor - results in Crash

### ISSUE THREAD

**Issue by SirSirom** [Globox1997/tiered#48]
When playing hovering over any type of armor with a modifier results in a crash due to "Unknown TooltipComponent"

[crash-2023-02-06_18.27.42-client.txt](https://github.com/Globox1997/tiered/files/10667567/crash-2023-02-06_18.27.42-client.txt)
[crash-2023-02-06_18.40.07-client.txt](https://github.com/Globox1997/tiered/files/10667598/crash-2023-02-06_18.40.07-client.txt)
[crash-2023-02-06_18.41.02-client.txt](https://github.com/Globox1997/tiered/files/10667601/crash-2023-02-06_18.41.02-client.txt)

this seems to be the case for all modified Armor items Including: Helmet, Chestplate, Leggings, Boots

possible solution much aprreciated

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/tiered/commit/aca317b23ed720b48a4cfbff76cc81398934b097](https://github.com/Globox1997/tiered/commit/aca317b23ed720b48a4cfbff76cc81398934b097)
