### ISSUE TITLE
Reforging Doesn't Work

### ISSUE THREAD

**Issue by BurnNova** [Globox1997/tiered#49]
In the Tiered mod  to reforge your gear the mod description says to add the metal of the gear on the left slot the gear in the middle slot and amethyst shard on the right slot but for some reason you cant put amethyst shard on the right slot please fix this issue or get rid of the need to add amethyst shard into the anvil.

**Comment by Globox1997** [comment]
If you play a modpack, the slot item might got changed.

**Comment by SalamiSid** [comment]
? Is there a fix for this or is it still an issue?

**Comment by Globox1997** [comment]
Reopen if this persist in the latest version + test if it happens when only this mod is installed and if yes, try figure out which mod makes trouble.
