### ISSUE TITLE
Encountered exception while handling in channel with name "tiered:set_screen"

### ISSUE THREAD

**Issue by Rad586** [Globox1997/tiered#50]
[latest.log.txt](https://github.com/Globox1997/tiered/files/10718863/latest.log.txt)
Mod version: 1.1.1
Game version: 1.18.2 fabric
Environment: Heavily modded
Steps to reproduce: 
1. Put down a anvil
2. Open it's gui
3. Click reforging button(If not success, back to step 1)

I'm not sure the incompatible mod since I have no idea what can cause this...
The gui works fine when it's only running with cloth config and fabric api.

**Comment by Globox1997** [comment]
Might be an incompatibility issue, maybe with BCLib.
Out of time reasons I don't work on older versions.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/c6a4038e7b00ff91a40408101ef61dde17031847](https://github.com/Globox1997/tiered/commit/c6a4038e7b00ff91a40408101ef61dde17031847)
