### ISSUE TITLE
Innate tooltips disappear in some cases

### ISSUE THREAD

**Issue by halflumi** [Globox1997/tiered#52]
Using 1.2.4, looks like the original tooltips of an item sometimes disappear (see examples and screenshots below). It would probably make the tooltips more consistent by displaying either the innate stats and modifiers separately (like in Example 3) or the accumulated final results.

Example 1, an Iron Helmet of `tiered:uncommon_armor_2` displays "-1 Armor" when in fact, it provides 1 armor because the helmet provides 2 armor by itself:

![image](https://user-images.githubusercontent.com/26127286/227702213-e47ad828-9ca6-43ab-bce8-f61f6197e0ac.png)

Example 2, a Diamond Helmet of `tiered:common_armor_4` only shows armor attributes. The "+2 Armor Toughness" disappears even though the tiered attributes don't change armor toughness:

![image](https://user-images.githubusercontent.com/26127286/227702247-b871cd9e-066c-461b-ad67-51ba2ad7c19f.png)

Example 3, a Diamond Helmet of `tiered:uncommon_armor_4` displays both the innate armor stat and tiered modifier, though the armor toughness is still missing:

![image](https://user-images.githubusercontent.com/26127286/227702414-dfcd2828-8634-44f2-8f86-958f9cebc289.png)

**Comment by Globox1997** [comment]
This is probably a mod incompatibility or does this happen with only tiered + deps installed

**Comment by halflumi** [comment]
Well, it didn't occur to me that this would be an incompatibility issue. This doesn't happen with only Tiered installed (screenshot below). It looks like the issue is caused by [PlayerEx](https://www.curseforge.com/minecraft/mc-mods/playerex), which probably falls out of the scope of tiered. Thanks for your prompt response!

P.S. During testing with only Tiered installed, the modifier that decreases durability doesn't seem to work. I'll open a new thread for that.

![image](https://user-images.githubusercontent.com/26127286/227760588-a6d94367-40a4-4994-8d72-25ac0b665c72.png)
