### ISSUE TITLE
Modifiers that decrease durability don't work

### ISSUE THREAD

**Issue by halflumi** [Globox1997/tiered#53]
In 1.2.4, modifiers that decrease durability don't work. An Iron Sword with -30% durability would have 175 durability, though it stays at 250 unchanged:

![image](https://user-images.githubusercontent.com/26127286/227761042-212bbca8-fec6-4938-98b6-e37e7e9ae5c0.png)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/118a31ef2eb7fb9eec3c953647ccc047d085a452](https://github.com/Globox1997/tiered/commit/118a31ef2eb7fb9eec3c953647ccc047d085a452)
