### ISSUE TITLE
Tier is always Epic if you have too much luck

### ISSUE THREAD

**Issue by jmadarg** [Globox1997/tiered#54]
This issue was first found by someone on a server using relics (from the [RelicEx](https://www.curseforge.com/minecraft/mc-mods/relicex) mod, the server uses the latest MMC1-Fabric modpack) that gave luck. They noticed every time they reforged an item, it was always Epic.

I tested this on singleplayer by only giving me the luck effect (as the relics are hard to replicate), and noticed the issue started at around luck 40~45, but you could get other (better) tiers from time to time. Starting at luck 50 the only tier when reforging is Epic.

I know is a bit of an edge case, but one would expect that with better luck you would get better tiers and not get stuck only with Epic.

Thanks in advance!

**Comment by Globox1997** [comment]
I've tested this and it works fine for me. By vanilla the player will never see such a high effect lvl btw^^
Change the config setting called luck_reforge_modifier to a lower value to reduce the effect of luck.
