### ISSUE TITLE
Any reason on why this datapack doesn't work for 1.18.2?

### ISSUE THREAD

**Issue by ShadOhh** [Globox1997/tiered#55]
[datapack 1.18.2.zip](https://github.com/Globox1997/tiered/files/11117517/datapack.1.18.2.zip)

I'm trying to make changes through datapack for 1.18.2, it loaded fine and everything but when trying to craft it wouldn't apply any of the tiers just the common iron chestplate

**Comment by ShadOhh** [comment]
any idea what's wrong?

**Comment by xR4YM0ND** [comment]
Change version 8 to version 9 when you play 1.18.2 in your pack.mcmeta

https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack#:~:text=1.18%20%2D%201.18.1-,9%20for%20versions,-1.18.2

**Comment by ShadOhh** [comment]
Even with 9 it still didn't work. I used the datapack provided through the 1.18.2 git repo i only changed the weight and some attributes. I don't know if i did something wrong or did the weight have to add up to 100?

**Comment by xR4YM0ND** [comment]
Oh yeah , your folder structure isnt correct

Put all folders in the folder item_attributes

**Comment by ShadOhh** [comment]
I moved all files into item_attributes it still doesn't work

**Comment by ShadOhh** [comment]
Does the weight value have to add up to less than or equal to 100? Cause that's the only thing i can think of that might be preventing it from generating.

**Comment by Revvilo** [comment]
To double check you have it like this?
`Tiered Changes\data\tiered\item_attributes\` and then all your folders (such as `all`, `melee_weapons`, etc)

**Comment by xR4YM0ND** [comment]
Send your latest.log pls

**Comment by Globox1997** [comment]
If this persist on the latest version, reopen this issue.
