### ISSUE TITLE
Easy Anvils Incompatibility

### ISSUE THREAD

**Issue by thrasos-dev** [Globox1997/tiered#58]
I'm having an issue with the reforging tabs not being displayed. Before the assets were moved to a library mod this issue did not occur. After removing Easy Anvils, the issue is resolved.
1. The tabs are not visible but they are clickable.
<img width="1552" alt="Screenshot 2023-04-05 at 12 35 43" src="https://user-images.githubusercontent.com/100732009/230057853-233b7f0b-ae85-455c-a3e2-497646ecb3a9.png">
2. After clicking on the right tab both tabs appear.
<img width="1552" alt="Screenshot 2023-04-05 at 12 35 54" src="https://user-images.githubusercontent.com/100732009/230057875-e0b4368f-e46b-4e14-9ad3-8af54dbeddd1.png">
<img width="1552" alt="Screenshot 2023-04-05 at 12 35 58" src="https://user-images.githubusercontent.com/100732009/230057881-fa6a7d31-90ea-4789-9537-9222ac9f6aa7.png">
3. After exiting the anvil and accessing it again, the tabs disappear.
<img width="1552" alt="Screenshot 2023-04-05 at 12 35 43" src="https://user-images.githubusercontent.com/100732009/230057853-233b7f0b-ae85-455c-a3e2-497646ecb3a9.png">

**Comment by SquareBall789** [comment]
same issue but i cant click the tab

**Comment by Globox1997** [comment]
Added partly compat with [https://github.com/Globox1997/tiered/commit/565e64d7bc1851863dcc9e76a765a8fff668d35c](https://github.com/Globox1997/tiered/commit/565e64d7bc1851863dcc9e76a765a8fff668d35c)
Imo easy anvils should use the old screen and not create a new one - reason for only partly compat
