### ISSUE TITLE
Option to remove bonus health from tools?

### ISSUE THREAD

**Issue by Razatop** [Globox1997/tiered#59]
Swapping between tools and loosing health when doing so is frustrating for the group that I play with. Would it be possible to add a config option that enables/disables bonus health?

**Comment by Globox1997** [comment]
You can do that by editing the default datapack

**Comment by Razatop** [comment]
> You can do that by editing the default datapack

You mean opening up the JAR and editing it correct? Just making sure as I saw no mentions of datapacks in other spots. Thanks for the response!

**Comment by Globox1997** [comment]
No you can create a separate datapack which overrides the default one.
