### ISSUE TITLE
[1.18.2 Feature] Option to Disable New Chest Tiers

### ISSUE THREAD

**Issue by itsdinkd** [Globox1997/tiered#6]
Would love to have a option available in config to disable the new update's feature on randomizing tiers on gear found in chests. This way I can make it how it existed prior to this update, basing it only on gear crafted/created.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/tiered/commit/e15666aab478ba3681302b5eed358b78064b369f](https://github.com/Globox1997/tiered/commit/e15666aab478ba3681302b5eed358b78064b369f)
