### ISSUE TITLE
Having an issue with the latest version of the 1.18.2 version with tools with health modifiers giving me the damaging screen shake whenever I unequip them

### ISSUE THREAD

**Issue by NoMoreCats7** [Globox1997/tiered#60]
Started noticing this after plucking some mods from a modpack and noticed this when I made my own personal one. Not sure if its interacting with a mod weirdly. Can offer mod list if needed

**Comment by Globox1997** [comment]
This got fixed in a later version (1.19+), out of time reasons I only work on the latest version of my mods.
