### ISSUE TITLE
Unable to open reforge screen when using chipped or damaged anvil

### ISSUE THREAD

**Issue by fowlerdylan** [Globox1997/tiered#62]
Issue: can't access reforge screen using chipped or damaged anvil.

Steps to reproduce:
1. Use Minecraft 1.18.2, Fabric loader 0.14.19, Fabric API 0.76.0, cloth config 6.3.81, tieredZ 1.1.1.
2. attempt to use the reforge screen on a chipped or damaged anvil.
3. observe that the screen closes itself.

I can't use libZ on 1.18.2 as the 1.19 version is the only one available on curseforge. I think that may be the fix to my issues.

**Comment by Globox1997** [comment]
Mh out of time reasons I only work on the latest versions of my mods.

**Comment by Globox1997** [comment]
This got fixed in a later version.
