### ISSUE TITLE
Bows dealing random damage between 0-20 no matter tier

### ISSUE THREAD

**Issue by slovinsqui** [Globox1997/tiered#64]
I saw someone else having this problem in the issues page, closed because it got tagged with a won´t fix in another mod´s github saying it must be an incompatibility

I decided to remove the rest of the mods in my modpack to test it myself, as a result the inconsistencies still happen, only having two mods

some times there is no damage at all, but there is knockback and damage flashing

mods: one that indicates damage inflicted and a datapack displaying the mobs health

https://www.planetminecraft.com/data-pack/splatus-vanilla-refresh-quality-of-life/

https://www.curseforge.com/minecraft/mc-mods/damage-indicator-mod

maybe it´s not about incompatibility (or intentional??) but i dunno, im not a coder

**Comment by Globox1997** [comment]
Have to look into this, which mod version?

**Comment by slovinsqui** [comment]
Minecraft 1.19.2
fabric 0.14.19
TieredZ 1.2.6

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/tiered/commit/55c2830657654fe6f1ab45166b8299119f5aff27](https://github.com/Globox1997/tiered/commit/55c2830657654fe6f1ab45166b8299119f5aff27)

**Comment by slovinsqui** [comment]
I ran a quick test and it seems that the non damaging shot is gone, but the 20 damage to bows with no current tier is still there, I don't have time to test this at the moment but i'll check it out later

**Comment by slovinsqui** [comment]
yeah, the 0 damage thing is gone, but the normal bows still reach 19 damage (without enchantments)

**Comment by Globox1997** [comment]
If the player has crit chance that might be possible yea :)

**Comment by slovinsqui** [comment]
oooh that's a thing??? my bad lol
how does it work tho?

**Comment by Globox1997** [comment]
If you have positive range crit chance, you might do more damage vice versa.

**Comment by slovinsqui** [comment]
do players get a default crit chance without armors?

**Comment by Globox1997** [comment]
armor should not give crit chance at all but the bow for example can give crit chance

**Comment by slovinsqui** [comment]
wait, so crits can still happen regardless of the crit chance stat? I thought non tiered bows had no crits at all, i mean, that´s what I understood lol
is there a way to tweak crit chances and critical damage?

btw sorry if Im being too insistent lol

**Comment by Globox1997** [comment]
If bows have no tier, armor can give crit chance too
Without crit chance, it doesn't affect the vanilla mechanic

**Comment by slovinsqui** [comment]
oh, well I get 20 dmg crits with non tiered bows even with no armor equiped, that´s what got me confused in the first place
Is that intented?

**Comment by Globox1997** [comment]
No this is not intended

**Comment by slovinsqui** [comment]
Just cheking in, is there going to be a fix for this version?

**Comment by acanthii** [comment]
Can confirm that this mod alone makes standard bows (bows pulled from the creative inventory without any tier) more OP

Non-tiered bow damage without mod installed: 8-10
Non-tiered bow damage with mod installed: 12-19

I suspect the issue lies here, you're modifying the damage the bow outputs to be the regular damage plus what crit damage would be 
https://github.com/Globox1997/tiered/blob/1.20/src/main/java/draylar/tiered/mixin/BowItemMixin.java

**Comment by acanthii** [comment]
```
persistentProjectileEntity.setDamage(
                persistentProjectileEntity.getDamage() + AttributeHelper.getExtraCritDamage((PlayerEntity) persistentProjectileEntity.getOwner(), (float) persistentProjectileEntity.getDamage()));
    }
```

the getExtraCritDamage already returns oldDamage, so by adding it TO persistentProjectileEntity.getDamage() you're effectively doubling your damage for bows
I compiled a version without persistentProjectileEntity.getDamage() and it seems to work better

**Comment by Globox1997** [comment]
Thank you @snoandpetals 
fixed with [https://github.com/Globox1997/tiered/commit/da0d2b7123822461bf0cc9edeac7d38422b3544e](https://github.com/Globox1997/tiered/commit/da0d2b7123822461bf0cc9edeac7d38422b3544e)
