### ISSUE TITLE
+Max Health Not Working Correctly

### ISSUE THREAD

**Issue by IcyJalapeno** [Globox1997/tiered#66]
Bounce SMP 1.4.1 || Minecraft 1.18.2 || Fabric API 0.76.0 || Cloth Config 6.4.90 || Tiered 1.1.1

*Going to post this in both place just in case.

Issue: +Max Health on Armor Pieces seems to be in constant flux of having the extra health or not. Taking off and re-equipping the armor on occasion fixes the problem temporary. However, randomly my max health drops, to baseline or that I'm only wearing one piece with Bonus Health. Armor Value seems inconsistent as well.

**Comment by Globox1997** [comment]
Yes this was an issue back in the 1.18.2 version. This got later fixed.
Out of time reasons I only work on the latest version, feel free to fix it :)
