### ISSUE TITLE
Tieredz armor stands reforge unmodified armor

### ISSUE THREAD

**Issue by Magmati55** [Globox1997/tiered#67]
If you equip an armor stand with an unmodified armor piece, it reforges it

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/8e5eda279b5cb5f0eceadd1f35212a55181d6378](https://github.com/Globox1997/tiered/commit/8e5eda279b5cb5f0eceadd1f35212a55181d6378)
