### ISSUE TITLE
Items doesn't seem to have the required tags for reforge

### ISSUE THREAD

**Issue by PoulpY2K** [Globox1997/tiered#68]
### Minecraft Version

1.19.x

### Mod Loader Version

1.14.19

### Mod Version

1.2.7

### Describe the Issue

**Issue :** Can't reforge stuff because the required items don't have the right tags

I have been trying to reforge some of my items, but I couldn't put the amethyst shard inside the right slot on the reforge tab.
After a bit of research, I found on your page that the Amethyst Shard and the required ingots should have the right tags in order to be used in the reforge.

Weirdly enough, Flint seems to have the right tag, but the amethyst and my ingots doesn't. Is there a way to fix it in some config files by myself ?

Thank you in advance and have a beautiful week. I'll upload some screenshots to make the subject clearer.

![2023-05-10_00 54 42](https://github.com/Globox1997/tiered/assets/35991042/e4fec70b-8bd3-4f86-9a9b-3b0c783ad7e2)
![2023-05-10_00 54 46](https://github.com/Globox1997/tiered/assets/35991042/459fa92d-3ab9-450d-a0d9-4b56a6547de2)
![2023-05-10_00 54 40](https://github.com/Globox1997/tiered/assets/35991042/21ff028c-6123-4e40-8c82-831b914cf43f)

### latest.log

[latest.log](https://github.com/Globox1997/tiered/files/11436727/latest.log)

I can also give you the server logs if needed.

### Do you use any other mods except the required ones?

Another Quality Modpack 2 (1.5.2)

**Comment by PoulpY2K** [comment]
Also, I realized it's probably irrelevant to ask you instead of the modpack creator because it surely is not your fault if the tags are breaking.
You can close the issue if you think I shouldn't post this here, sorry for the disturbance.

**Comment by PoulpY2K** [comment]
I found out what the right item was for the amethyst slot.
Closing the issue, because I think it comes from my modpack.

![2023-05-11_00 52 39](https://github.com/Globox1997/tiered/assets/35991042/632ee650-eac3-4ac0-9b66-fa0b748eb631)

**Comment by Globox1997** [comment]
Glad you figured it out :)
