### ISSUE TITLE
Cannot find Reforging Station

### ISSUE THREAD

**Issue by RealFilllykung** [Globox1997/tiered#69]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.19

### Mod Version

1.2.7

### Describe the Issue

I cannot find the item called Reforging Station. I also tried to use a command to set block, but I also cannot find the item group called "tiered". There is also no creative table for Tiered mod.

### latest.log

https://gist.github.com/RealFilllykung/8ef93b4d21d1bca5d08eb0c04f636f84

**Comment by RealFilllykung** [comment]
To add on from the post, here are the loaded mods I've used:
	- appleskin 2.4.1+mc1.19
	- architectury 6.5.82
	- autotag-convention 2.0.0+1.19
	   \-- autotag 2.0.0+1.19
	- balm-fabric 4.5.7
	- betterdeserttemples 1.19.2-Fabric-2.2.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.19.2-Fabric-3.2.1
	- betterf3 4.0.0
	- betterfortresses 1.19.2-Fabric-1.0.5
	- bettermineshafts 1.19.2-Fabric-3.2.0
	- betteroceanmonuments 1.19.2-Fabric-2.1.0
	- betterstrongholds 1.19.2-Fabric-3.2.0
	- betterwitchhuts 1.19.2-Fabric-2.1.0
	- bookshelf 16.2.18
	- byg 2.0.0.13
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- chefsdelight 1.0.3-fabric-1.19.2
	   \-- structurized-reborn 1.19-01
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- cobblemon 1.3.1+1.19.2
	- cobblemon_armor_plus 1.0.0
	- cobblepedia 0.4.3+1.19.2
	- ctov 3.2.0
	- entityculling 1.6.1-mc1.19.2
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- farmersdelight 1.19.2-1.3.9
	- ferritecore 5.0.3
	- fightorflight 0.4.11-12
	- forgeconfigapiport 4.2.11
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- geophilic 1.19-2.0.0b
	- handcrafted 2.0.6
	- illuminations 1.10.11
	- immediatelyfast 1.1.12
	   \-- net_lenni0451_reflect 1.1.0
	- indium 1.0.9+mc1.19.2
	- inventoryprofilesnext 1.9.7
	- java 18
	- jei 11.6.0.1015
	- lazydfu 0.1.3
	- libipn 2.0.7
	- libz 1.0.0
	- lithium 0.11.1
	- lootr 0.4.25.64
	- memoryleakfix 1.0.0
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- minecraft 1.19.2
	- moonlight 1.19.2-2.2.31
	- mousetweaks 2.22
	- notenoughanimations 1.6.2
	- oceansdelight 1.0.0
	- owo 0.8.5+1.19
	   \-- blue_endless_jankson 1.2.1
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- phosphor 0.8.1
	- resourcefullib 1.1.24
	- showmeyourskin 1.6.3+1.19.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cicada 0.4.0
	- smartbrainlib 1.9
	- sodium 0.4.4+build.18
	   \-- org_joml_joml 1.10.4
	- sound_physics_remastered 1.19.2-1.0.18
	- spark 1.10.37
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- supplementaries 1.19.2-2.3.10
	- t_and_t 1.9
	- terrablender 2.0.1.136
	- tiered 1.2.7
	   \-- reach-entity-attributes 2.3.0
	- travelersbackpack 1.19.2-8.2.20
	   \-- reach-entity-attributes 2.3.0
	- treechop 0.17.6
	- waystones 11.4.0
	- yungsapi 1.19.2-Fabric-3.8.9
	   \-- org_javassist_javassist 3.28.0-GA
	- yungsbridges 1.19.2-Fabric-3.1.0
	- yungsextras 1.19.2-Fabric-3.1.0

**Comment by Globox1997** [comment]
You can reforge items at the anvil.

**Comment by RealFilllykung** [comment]
I see. Thanks for the information. Now I see the reforge menu now.
![image](https://github.com/Globox1997/tiered/assets/45094470/0ca82997-b665-412a-aef9-910299952b4d)
