### ISSUE TITLE
Shift-clicking tool/armor trades from villagers doesn't apply modifiers.

### ISSUE THREAD

**Issue by PaulZappia** [Globox1997/tiered#7]
When buying tools and armor from toolsmiths, armorers or weaponsmiths, modifers seem to only be applied if they are purchased one at a time. If you try to buy out an item by shift-clicking the trade, no modifers will be applied to the gear.

Video of the bug in question:
https://drive.google.com/file/d/1IAoQoaACdnlo97M3l3m_OLzbAkSgYw2U/view

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/16f0d3430e4871badbb65782189a1842cf172fb9](https://github.com/Globox1997/tiered/commit/16f0d3430e4871badbb65782189a1842cf172fb9) thanks for reporting
