### ISSUE TITLE
Treat the axe as a weapon and let it get attack damage modifiers/luck

### ISSUE THREAD

**Issue by phDoenix** [Globox1997/tiered#71]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Simple as that. I didn't realize till now that swords get a % based increase on their damage if they have the right attributes and as an axe player, it would be nice to get those changes on an axe as well, even if there needs to be a reduction for balancing purposes or otherwise.

**Comment by phDoenix** [comment]
Figured it out on my own after sniffing around the the .jar files. Just added the "c:axes" tag to all the melee weapon attributes

**Comment by Globox1997** [comment]
you don't have to modify the jar itself, just create a separate datapack.
