### ISSUE TITLE
Armor attributes not displaying correctly

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Globox1997/tiered#72]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

tiered-1.2.7

### Describe the Issue

When modifying data with a datapack, items with tiers which add armor toughness do not display said armor toughness unless the base item would already have a value (e.g. diamond chestplate, etc.).

Expected behavior would be that tiered items display in parentheses the additional toughness added, the same way other stats are displayed as additional

### latest.log

[latest.log](https://github.com/Globox1997/tiered/files/11938487/latest.log)

### Do you use any other mods except the required ones?

Currently using some other mods but issue persisted even in isolation

**Comment by Globox1997** [comment]
This is a vanilla issue.

**Comment by Globox1997** [comment]
Actually it is not. It is an edge case, fixed with [https://github.com/Globox1997/tiered/commit/e4d31a4f848b66ab16cf6cce8ecf3d571f395a41](https://github.com/Globox1997/tiered/commit/e4d31a4f848b66ab16cf6cce8ecf3d571f395a41)
