### ISSUE TITLE
Elytra tiers don't work properly

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Globox1997/tiered#73]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

tiered-1.2.7

### Describe the Issue

When Elytra have any tier, no stats are modified except for durability, and no stats are displayed whatsoever. All that changes are cosmetic changes like item color and prefix, and again actual durability increases. When using a custom datapack that only allows durability changes in all available tiers, no durability change can be observed.

Expected behavior would be that Elytra can have the same stat modifiers as the rest of armor like additional defense, max health, etc.

### latest.log

[latest.log](https://github.com/Globox1997/tiered/files/11938529/latest.log)

### Do you use any other mods except the required ones?

Some other mods being used, but issue persists in isolation

**Comment by Globox1997** [comment]
Fixed behavior and added elytra tier with [https://github.com/Globox1997/tiered/commit/e1054d12b2c8be797427eddfa3c3a279a13cec5d](https://github.com/Globox1997/tiered/commit/e1054d12b2c8be797427eddfa3c3a279a13cec5d)
