### ISSUE TITLE
Ranged crit chance in custom datapack has no effect

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Globox1997/tiered#74]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

tiered-1.2.7

### Describe the Issue

When modifying total crit chance percentage for ranged weapons in custom datapack, no observable change in damage output can be seen. Extensive testing has demonstrated no significant difference in damage range based on crit chance.

Vanilla "critical hit" mechanics for bows are ambiguous, since fully charged shots are all critical, so I'm not sure if the intended outcome is that bows drawn for less time will still launch critical arrows, or if fully charged shots will have an additional critical hit system applied, but in either case damage is the same as untiered bow, regardless of bow draw amount.

Critical hits for melee weapons seem functional, though crits can be forced with melee by jump-striking, but they still at least seem to work as intended.

### latest.log

[latest.log](https://github.com/Globox1997/tiered/files/11938569/latest.log)

### Do you use any other mods except the required ones?

Other mods in use but issue persists in isolation

**Comment by Globox1997** [comment]
Fixed on the latest version.
