### ISSUE TITLE
Durability Modifiers above 100% don't work properly

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Globox1997/tiered#75]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

tiered-1.2.7

### Describe the Issue

When making custom tiers that alter durability using the MULTIPLY_TOTAL operation, values equal to or greater than 1.0 (or +100%) display correctly in tooltips but only add 1 to durability total (e.g. iron pickaxe goes from default durability of 250 to 251 despite displaying"+200% durability")

### latest.log

[latest.log](https://github.com/Globox1997/tiered/files/11962981/latest.log)

### Do you use any other mods except the required ones?

Other mods used but issue persists in isolation

**Comment by TwentySeventhLetter** [comment]
Update, every whole number added by MULTIPLY_TOTAL adds 1 point of durability, so putting 120 as the multiplier displays "+12000% durability" but only adds 120 points to the default item durability

**Comment by Globox1997** [comment]
I think I fixed this in a later version, out of time reasons I only work on the latest versions of my mods.
Reopen if still persistent in latest version.
