### ISSUE TITLE
Reforging doesnt work

### ISSUE THREAD

**Issue by AlexLovelock22** [Globox1997/tiered#76]
### Minecraft Version

1.19.x

### Mod Loader Version

idk doesnt matter

### Mod Version

1.2.2

### Describe the Issue

Reforging literally doesnt do anything. Its broken.

### latest.log

no

### Do you use any other mods except the required ones?

Its from the Better Adventures + Modpack.

**Comment by Globox1997** [comment]
Update to a later version.
