### ISSUE TITLE
Wrong material for simply swords mythic metals compat

### ISSUE THREAD

**Issue by ZERv3** [Globox1997/tiered#78]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.2.7

### Describe the Issue

When trying to reroll tier on simply swords weapons made of mythic metals materials, the requiered material is always diamond.
<img width="443" alt="Снимок экрана 2023-07-29 в 13 14 01" src="https://github.com/Globox1997/tiered/assets/128105093/029dbf66-fc11-4cb0-9dfc-f1fa06080d40">
<img width="440" alt="Снимок экрана 2023-07-29 в 13 14 52" src="https://github.com/Globox1997/tiered/assets/128105093/de3ccbd9-2678-4a7a-bd35-7713dc040130">
<img width="453" alt="Снимок экрана 2023-07-29 в 13 14 10" src="https://github.com/Globox1997/tiered/assets/128105093/53754a36-8ca9-47f8-887f-a6460e8fe71a">

### latest.log

[latest.log](https://github.com/Globox1997/tiered/files/12206894/latest.log)

**Comment by Globox1997** [comment]
This can get changed via datapacks, check out the future readme
