### ISSUE TITLE
Tooltip Crash after hovering over item [1.20.1]

### ISSUE THREAD

**Issue by pewblaze** [Globox1997/tiered#79]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

tiered-1.2.7

### Describe the Issue

After hovering over an item in a chest in a village the game crashes. 

### latest.log

https://gist.github.com/pewblaze/b6a3e4ce84048bc25f0a30cfe31390ed

### Do you use any other mods except the required ones?

yes, it isnt happening with only the required ones ^^"

**Comment by KeylorV** [comment]
Same here, happens even when I just hover over an item in my inventory.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/84a2bc26107d53d0ceba9304bf577ac8ee86d6d0](https://github.com/Globox1997/tiered/commit/84a2bc26107d53d0ceba9304bf577ac8ee86d6d0)
