### ISSUE TITLE
Crashes when using other languages

### ISSUE THREAD

**Issue by ThatGravyBoat** [Globox1997/tiered#80]
### Minecraft Version

1.20.x

### Mod Loader Version

N/A

### Mod Version

N/A

### Describe the Issue

Due to usage of toLowerCase in [EquipmentSlotDeserializer](https://github.com/Globox1997/tiered/blob/1.20/src/main/java/draylar/tiered/gson/EquipmentSlotDeserializer.java#L15) it will switch keys because languages such as turkish have a different lowercase `i` and causes issues for something like `mainhand`. To fix this you should be using `toLowerCase(Locale.ROOT)`

### latest.log

N/A

**Comment by Globox1997** [comment]
Thanks for reporting and providing a fix, hopefully this fixed it [https://github.com/Globox1997/tiered/commit/bcdc3c0a071f17fc2d4b6aa5f749887699846647](https://github.com/Globox1997/tiered/commit/bcdc3c0a071f17fc2d4b6aa5f749887699846647)
