### ISSUE TITLE
Modifier Changes When Unequipped

### ISSUE THREAD

**Issue by YourAverageModder** [Globox1997/tiered#81]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22-1.20.1

### Mod Version

1.2.8

### Describe the Issue

Every time I unequip and reequip anything that can have a modifier, it completely re-rolls the modifiers. It'll keep doing it every time, doesn't matter what I do

### latest.log

https://gist.github.com/YourAverageModder/6d365f20c2ca391a681ef92d1ae9e503

### Do you use any other mods except the required ones?

_Yes i do use quite a lot of the other mods_

**Comment by Globox1997** [comment]
This happens due to a mod incompatibility. Please figure out which mod leads to this issues.

**Comment by Linguardium** [comment]
Legendary tooltips causes this when render_item_model is set to EQUIPMENT or ALL.

**Comment by Globox1997** [comment]
By the help of @Linguardium this got fixed with [https://github.com/Globox1997/tiered/commit/00117a7a3241101324d3263b45df30382b8d7d6e](https://github.com/Globox1997/tiered/commit/00117a7a3241101324d3263b45df30382b8d7d6e)
