### ISSUE TITLE
Missing string for Range attribute

### ISSUE THREAD

**Issue by Zano1999** [Globox1997/tiered#84]
### Minecraft Version

1.20.x

### Mod Loader Version

/

### Mod Version

/

### Describe the Issue

In the .lang file is missing the "Range" string so it cannot be translated in other languages.

![image](https://github.com/Globox1997/tiered/assets/42555362/4b11052e-471e-4cee-9b96-d36eaa988514)

![image](https://github.com/Globox1997/tiered/assets/42555362/cc63b33a-526e-4054-8736-486a8e5641cd)

### latest.log

/

**Comment by Globox1997** [comment]
I am using a lib, where the lang is used of [https://github.com/JamiesWhiteShirt/reach-entity-attributes/blob/1.19/src/main/resources/assets/reach-entity-attributes/lang/en_us.json](https://github.com/JamiesWhiteShirt/reach-entity-attributes/blob/1.19/src/main/resources/assets/reach-entity-attributes/lang/en_us.json)
