### ISSUE TITLE
Anti-dumb system

### ISSUE THREAD

**Issue by Fl414r** [Globox1997/tiered#86]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

I using 1.19.2 modpack with this mod and yes I need this system to stop skipping Uniques
I ask for system that blocks reforging for ~3-5 seconds after getting Unique (And some settings for this, for example, activate for Legendary/Epic items, or disable this mechanic)

**Comment by Globox1997** [comment]
Added a config option with [https://github.com/Globox1997/tiered/commit/f3be39c4fa8c2d552c52755b5eb01267bc4a4d3a](https://github.com/Globox1997/tiered/commit/f3be39c4fa8c2d552c52755b5eb01267bc4a4d3a)
Out of time reasons I only work on the latest versions of my mods.
