### ISSUE TITLE
Specific Traits System

### ISSUE THREAD

**Issue by thrasos-dev** [Globox1997/tiered#90]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

I found an issue asking for something similar but not quite the same.

Some players in my modpack have been asking for a way to choose specific traits for their items. This could be implemented as an end-game system that is very expensive to do, so as to keep it balanced.

**Comment by Globox1997** [comment]
Mh I have no plans to add such a system, players can already reroll the weapon stats.
Just released a SmitherZ mod which works with Tiered but also standalone and fits in your needs.
