### ISSUE TITLE
Is there a way to make this mod affect other attributes 

### ISSUE THREAD

**Issue by Korsun66** [Globox1997/tiered#93]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

besides just ranged damage and melee for example working with Wizards mod, or even just being able to reforge a staff from the mod?

**Comment by Globox1997** [comment]
yes, you can add your own datapack with every attributes you want, check out the readme :)
