### ISSUE TITLE
Reforge Crashes upon opening tab 

### ISSUE THREAD

**Issue by Jaycords** [Globox1997/tiered#94]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.2

### Mod Version

1.20.1 - 1.3.0

### Describe the Issue

reforge crashes upon opening the reforge menu i do have other mods i uninstalled them all and even that didn't work and i tried multiple times to reupdate the mod thinking i was on the wrong version 

### latest.log

[crash-2024-01-16_01.42.08-server.txt](https://github.com/Globox1997/tiered/files/13946423/crash-2024-01-16_01.42.08-server.txt)

### Do you use any other mods except the required ones?

yes.

**Comment by erdogndmn** [comment]
This issue caused by LibZ Mod. Try to download newest version.

**Comment by Globox1997** [comment]
As erdogndmn said, updated libz to the latest version.

**Comment by Jaycords** [comment]
got it fixed it was libz thank you 👍
