### ISSUE TITLE
Crashes when trying to reforge on an anvil

### ISSUE THREAD

**Issue by SleepyZeta** [Globox1997/tiered#95]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric-loader-0.15.2-1.20.1

### Mod Version

1.3.0

### Describe the Issue

Game give a crash report after clicking on the reforge tab in the anvil.

### latest.log

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-01-17 17:42:23
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/libz/network/LibzServerPacket
	at draylar.tiered.network.TieredServerPacket.lambda$init$2(TieredServerPacket.java:43)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.libz.network.LibzServerPacket
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 983739096 bytes (938 MiB) / 3275751424 bytes (3124 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.21
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c60
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4633
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28528.00
	Virtual memory used (MB): 17785.72
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.11
		adventurez: AdventureZ 1.4.18
		ambientsounds: AmbientSounds 5.2.20
		amplified_nether: Amplified Nether 1.2.2
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		auditory: Auditory 0.0.6-1.20.1
		autotag-convention: AutoTag Convention 2.0.2+1.20
			autotag: AutoTag 2.0.2+1.20
		bedspreads: Bedspreads 6.2.0+1.20.1
		betteradvancements: Better Advancements 0.3.2.161
		bettercombat: Better Combat 1.8.3+1.20.1
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
			org_reflections_reflections: reflections 0.10.2
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterthirdperson: Better Third Person 1.9.0
		blur: Blur (Fabric) 3.1.0
			satin: Satin 1.13.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		cavedust: Cave Dust 1.4.1
			kirin: Kirin UI 1.15.0
		cherishedworlds: Cherished Worlds 6.1.0+1.20.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 6.3.4+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			spectrelib: SpectreLib 0.13.14+1.20.1
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		continents: Continents 1.1.4
		creativecore: CreativeCore 2.10.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		cupboard: cupboard 1.20.1-2.1
		dataloader: Data loader 1.1.3+1.19.4-1.20-pre5
		diagonalfences: Diagonal Fences 8.0.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		easyanvils: Easy Anvils 8.0.0
		easymagic: Easy Magic 8.0.0
		eatinganimationid: Eating Animation 1.9.4+1.20
		entity_model_features: Entity Model Features 0.2.13
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		extrasounds: ExtraSounds 2.3.1+1.20.1~lonefelidae16-build.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			soundcategories: Sound Categories 1.2.4+1.20~lonefelidae16-build.1
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.2
			mixinextras: MixinExtras 0.3.2
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		fallingtree: FallingTree 4.3.4
		farsight: Farsight Mod 1.20.1-4.2
			org_jctools_jctools-core: jctools-core 4.0.1
		firstperson: FirstpersonModel 2.2.3
		forgeconfigapiport: Forge Config API Port 8.0.0
		herdspanic: Herds Panic 1.0.7
		iceberg: Iceberg 1.1.18
		incendium: Incendium 5.3.4
		inmis: Inmis 2.7.2-1.20.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		inmisaddon: InmisAddon 1.0.4
		invmove: InvMove 0.8.4
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemborders: Item Borders 1.2.1
		jamlib: JamLib 0.6.0+1.20
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.18
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.4.4
		libz: LibZ 1.0.1
		lithium: Lithium 0.11.2
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.1.0
		morebannerfeatures: More Banner Features 1.2.0
		moremobvariants: More Mob Variants 1.2.2
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		notenoughanimations: NotEnoughAnimations 1.6.4
		nullscape: Nullscape 1.2.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.0
		prism: Prism 1.0.5
		puzzleslib: Puzzles Lib 8.0.7
		replaymod: Replay Mod 1.20.1-2.6.13
		repurposed_structures: Repurposed Structures 7.0.0+1.20-fabric
		rightclickharvest: Right Click Harvest 3.2.2+1.19.x-1.20.1-fabric
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		simplyswords: Simply Swords 1.51.5-1.20.1
			spruceui: SpruceUI 5.0.0+1.20
		smoothswapping: Smooth Swapping 0.9.3.1
		sodium: Sodium 0.5.3
		soulfired: Soul fire'd 3.2.0.0
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.1
		structory: Structory 1.3.4
		terralith: Terralith 2.4.11
		tiered: Tiered 1.3.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		tinyskeletons: Tiny Skeletons 8.0.0
		trade_cycling: Trade Cycling 1.20.1-1.0.5
		trinkets: Trinkets 3.7.1
		universalbonemeal: Universal Bone Meal 8.0.0
		vanillatweaks: VanillaTweaks 1.5.69
		visuality: Visuality 0.7.0+1.20
		wakes: Wakes 0.1.6
			blue_endless_jankson: jankson 1.2.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
		zoomify: Zoomify 2.11.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['RooKait'/190, l='ServerLevel[Ark of Terra]', x=89.04, y=64.00, z=170.00]]
	Data Packs: vanilla, fabric, file/BlazeandCaves Advancements Pack 1.16.1 (1).zip, file/New-Desert-Temple.zip (incompatible), file/New-End-Cities.zip (incompatible), file/New-Ocean-Ruins.zip (incompatible), file/New-Ruined-Portals.zip (incompatible), file/Terralith_1.20_v2.4.6.zip, file/vanillarefresh-v1.4.16d.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.2-1.20.1

### Do you use any other mods except the required ones?

yes, but nothing that would interfere with how the anvil or items being reforged worked, although there is a high possibility that i might be wrong

**Comment by Globox1997** [comment]
Update LibZ
