### ISSUE TITLE
[help] anvil tab texture cant be retextured

### ISSUE THREAD

**Issue by maoperson** [Globox1997/tiered#96]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

its not a real feature suggestion but its not a bug either.

as you can see the tab texture is not textured:
![image](https://github.com/Globox1997/tiered/assets/98748787/f9b9ab2e-9fb9-473c-adbe-aeb319d39265)

and i cant find any file that would modify it:
![image](https://github.com/Globox1997/tiered/assets/98748787/39833bf9-cd67-49c5-b44c-7bbfe9fcd8de)

idk if this is mod or vanilla related, but in the vanilla anvil texture there are also no tab textures that could be retextured

**Comment by Globox1997** [comment]
Check out libZ

**Comment by maoperson** [comment]
NICE
